"""add participante table

Revision ID: 84f1e15cedd1
Revises: 20240209_0002
Create Date: 2026-02-11 20:30:13.932096

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84f1e15cedd1'
down_revision = '20240209_0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('participantes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=False),
    sa.Column('data_cadastro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('perfil', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telefone')
    )
    op.create_index(op.f('ix_participantes_id'), 'participantes', ['id'], unique=False)
    op.drop_table('usuarios_normais')
    op.create_index(op.f('ix_usuarios_admin_id'), 'usuarios_admin', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_admin_id'), table_name='usuarios_admin')
    op.create_table('usuarios_normais',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('senha_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('funcao', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='usuarios_normais_pkey'),
    sa.UniqueConstraint('email', name='uq_usuarios_normais_email', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_index(op.f('ix_participantes_id'), table_name='participantes')
    op.drop_table('participantes')
    # ### end Alembic commands ###
