"""adicionando coluna

Revision ID: b3477bb87afc
Revises: 8c3fd2f15ac3
Create Date: 2026-02-12 14:22:32.108739

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3477bb87afc'
down_revision = '8c3fd2f15ac3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participantes', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participantes', 'is_active')
    # ### end Alembic commands ###
